apiVersion: v1
kind: Secret
metadata:
  name: pfa-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: pfa
  GMAIL_USERNAME: ""
  GMAIL_APP_PASSWORD: ""
  KEYCLOAK_ADMIN_CLIENT_SECRET: rexel-mini-store-service-secret-local-dev
