server:
  port: 8081

spring:
  application:
    name: rexel-mini-store

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/rexel_store}
    username: pfa
    password: pfa

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/rexel-realm

app:
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8180}
    realm: rexel-realm
    admin-client-id: rexel-mini-store-service
    admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:rexel-mini-store-service-secret-local-dev}
